crop_name: winter wheat

single_value_params:
  # TEFFMX:
  #   type: float
  #   low: 25.0
  #   high: 40.0
  #   precision: 2

  TSUM1:
    type: int
    low: 800
    high: 1700

  TSUM2:
    type: int
    low: 800
    high: 1700

multi_value_params:
  RUETableRUE:
    type: float
    values:
      - { low: 2.5, high: 3.5 }
      - { low: 3.0, high: 4.0 }
      - { low: 3.0, high: 4.0 }
      - { low: 3.0, high: 4.0 }
    precision: 2
