crop_name: winter wheat

simplace_paths:
  install_dir: simplace_portable/workspace/
  work_dir: simulation-optuna/
  output_dir: simulation-optuna/output/
  solution_file: simulation-optuna/SimulationExperimentTemplateTest/solution/Soil3_Germany_AllKreis_Test.sol.xml
  project_file: simulation-optuna/SimulationExperimentTemplateTest/project/Soil3_Germany_AllKreis.proj.xml

local:
  single_value_params: 
    TEFFMX:
      type: float
      low: 25.0
      high: 40.0
      precision: 2  

    TSUM1:
      type: int
      low: 800
      high: 1700

    TSUM2:
      type: int
      low: 800
      high: 1700

  multi_value_params:
    RUETableRUE:
      type: float
      values:
        - { low: 2.5, high: 3.5 }
        - { low: 3.0, high: 4.0 }
        - { low: 3.0, high: 4.0 }
        - { low: 3.0, high: 4.0 }
      precision: 2

cluster:
  single_value_params:
    TEFFMX:
      type: float
      low: 25.0
      high: 40.0
      precision: 2

    TSUM1:
      type: int
      low: 800
      high: 1700

    TSUM2:
      type: int
      low: 800
      high: 1700

  multi_value_params:
    RUETableRUE:
      type: float
      values:
        - { low: 2.5, high: 3.5 }
        - { low: 3.0, high: 4.0 }
        - { low: 3.0, high: 4.0 }
        - { low: 3.0, high: 4.0 }
      precision: 2
